<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MenuSeeder extends Seeder
{
    public function run()
    {
        DB::table('menus')->insert([
            // Makanan
            [
                'name' => 'Nasi Goreng',
                'description' => 'Nasi goreng spesial dengan bumbu rempah khas Indonesia',
                'price' => '20000',
                'image' => '/images/nasigoreng.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mie Ayam',
                'description' => 'Mie ayam lezat dengan potongan ayam dan pangsit',
                'price' => '18000',
                'image' => '/images/mieayam.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sate Ayam',
                'description' => 'Sate ayam dengan bumbu kacang yang gurih',
                'price' => '25000',
                'image' => '/images/sateayam.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rendang',
                'description' => 'Rendang daging sapi khas Padang yang kaya rempah',
                'price' => '35000',
                'image' => '/images/rendang.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Burger',
                'description' => 'Burger daging sapi dengan keju dan sayuran segar',
                'price' => '40000',
                'image' => '/images/burger.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pizza Margherita',
                'description' => 'Pizza Italia klasik dengan saus tomat dan keju mozzarella',
                'price' => '50000',
                'image' => '/images/pizza.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Spaghetti Bolognese',
                'description' => 'Spaghetti dengan saus daging sapi bolognese',
                'price' => '45000',
                'image' => '/images/spaghetti.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ayam Bakar',
                'description' => 'Ayam bakar bumbu kecap manis dengan sambal',
                'price' => '28000',
                'image' => '/images/ayambakar.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ikan Bakar',
                'description' => 'Ikan bakar segar dengan sambal dabu-dabu',
                'price' => '30000',
                'image' => '/images/ikanbakar.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Steak',
                'description' => 'Steak daging sapi dengan saus lada hitam',
                'price' => '60000',
                'image' => '/images/steak.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Soto Ayam',
                'description' => 'Soto ayam hangat dengan koya dan sambal',
                'price' => '22000',
                'image' => '/images/sotoayam.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lasagna',
                'description' => 'Lasagna Italia dengan lapisan daging dan keju',
                'price' => '48000',
                'image' => '/images/lasagna.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bakso',
                'description' => 'Bakso sapi kenyal dengan kuah kaldu gurih',
                'price' => '18000',
                'image' => '/images/bakso.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ayam Geprek',
                'description' => 'Ayam goreng crispy dengan sambal pedas',
                'price' => '23000',
                'image' => '/images/ayamgeprek.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chicken Wings',
                'description' => 'Sayap ayam goreng dengan saus BBQ',
                'price' => '35000',
                'image' => '/images/chickenwings.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Minuman
            [
                'name' => 'Es Teh Manis',
                'description' => 'Es teh manis segar',
                'price' => '8000',
                'image' => '/images/estehmanis.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jus Alpukat',
                'description' => 'Jus alpukat segar dengan susu kental manis',
                'price' => '15000',
                'image' => '/images/jusalpukat.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kopi Hitam',
                'description' => 'Kopi hitam panas tanpa gula',
                'price' => '10000',
                'image' => '/images/kopihitam.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Milkshake Cokelat',
                'description' => 'Milkshake cokelat dingin dan creamy',
                'price' => '18000',
                'image' => '/images/milkshake.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Teh Tarik',
                'description' => 'Teh tarik manis dengan buih lembut',
                'price' => '12000',
                'image' => '/images/tehtarik.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Es Jeruk',
                'description' => 'Es jeruk segar dengan perasan jeruk asli',
                'price' => '9000',
                'image' => '/images/esjeruk.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cappuccino',
                'description' => 'Cappuccino hangat dengan taburan cokelat',
                'price' => '20000',
                'image' => '/images/cappuccino.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Smoothie Strawberry',
                'description' => 'Smoothie strawberry segar dan sehat',
                'price' => '17000',
                'image' => '/images/smoothie.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Es Kopi Susu',
                'description' => 'Es kopi susu kekinian dengan gula aren',
                'price' => '18000',
                'image' => '/images/eskopisusu.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Green Tea Latte',
                'description' => 'Green tea latte dengan susu segar',
                'price' => '19000',
                'image' => '/images/greentea.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mojito',
                'description' => 'Mojito segar dengan daun mint dan lemon',
                'price' => '21000',
                'image' => '/images/mojito.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Es Kelapa Muda',
                'description' => 'Es kelapa muda segar langsung dari kelapa',
                'price' => '15000',
                'image' => '/images/eskelapa.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Latte',
                'description' => 'Kopi latte lembut dengan foam susu',
                'price' => '20000',
                'image' => '/images/latte.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Es Cendol',
                'description' => 'Es cendol manis dengan santan dan gula merah',
                'price' => '12000',
                'image' => '/images/escendol.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Air Mineral',
                'description' => 'Air mineral dingin',
                'price' => '5000',
                'image' => '/images/airmineral.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
